### ISSUE TITLE
GenServer SNMP.DiscoveryAgent terminating

### ISSUE THREAD

**Issue by goldcode88** [jonnystorm/snmp-elixir#34]
Run example in readme. It returns failure.

Interactive Elixir (1.7.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> SNMP.Supervisor.start_link([])
{:ok, #PID<0.207.0>}
iex(2)> 
21:30:25.441 [info]  SNMP agent.conf created - {:error, {:enoent, 'agent.conf'}}
 
21:30:25.466 [error] GenServer SNMP.DiscoveryAgent terminating
** (MatchError) no match of right hand side value: {:error, :enoent}
    (snmp_ex) lib/snmp/discovery_agent.ex:68: SNMP.DiscoveryAgent.do_seed_config/4
    (snmp_ex) lib/snmp/discovery_agent.ex:129: SNMP.DiscoveryAgent.seed_standard_config/1
    (snmp_ex) lib/snmp/discovery_agent.ex:50: SNMP.DiscoveryAgent.seed_config/1
    (snmp_ex) lib/snmp/discovery_agent.ex:42: SNMP.DiscoveryAgent.handle_cast/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:seed_and_start_agent, []}}
State: []
 
21:30:25.512 [info]  SNMP agent.conf created - {:ok, [intAgentUDPPort: 6000, intAgentTransports: [transportDomainUdpIpv4: {{127, 0, 0, 1}, 6000}, transportDomainUdpIpv6: {{0, 0, 0, 0, 0, 0, 0, 1}, 6000}], snmpEngineID: [128, 0, 0, 0, 6], snmpEngineMaxMessageSize: 484]}
 
21:30:25.529 [info]  SNMP standard.conf created - {:ok, [sysName: 'Discovery agent', sysDescr: 'Discovery agent', sysContact: [], sysLocation: [], sysObjectID: [3, 6, 1, 4, 1, 193, 19], sysServices: 72, snmpEnableAuthenTraps: :disabled]}
 
21:30:25.578 [info]  Starting snmp agent...

**Comment by jonnystorm** [comment]
I believe #35 will fix any problems you were seeing. Note that you should now simply add `:snmp_ex` to `extra_applications` in your application environment. Elixir will do the rest.

Please let me know if you run into trouble, and thanks for contributing!

**Comment by goldcode88** [comment]
Thank you for your fast reply! It works well now.
