### ISSUE TITLE
API Refactor

### ISSUE THREAD

**Issue by jonnystorm** [jonnystorm/snmp-elixir#42]
I realize the current API is a bit broken in light of SNMP set (see #41). See the [latest `NetSNMP` API](https://gitlab.com/jonnystorm/net-snmp-elixir/blob/master/lib/net_snmp2.ex#L400) for my ideas about how to fix it. If we're going to make breaking changes, it may be worth breaking things in that direction.

As for the credential API, this should probably be cut down to accepting a simple map. Maintaining two different ordinal input methods is a bit silly, even for me. Recent efforts to push credential generation/translation into its own module (see #40) are a good indicator that the excessive amount of code here is more of a distraction than it should be.

**Comment by fbettag** [comment]
Any updates on this? :) i would really like to switch over from net-snmp-elixir.

**Comment by jonnystorm** [comment]
@fbettag Thanks for your interest! #42 has been merged, and I'll be pushing 0.3.1 to Hex shortly.

**Comment by fbettag** [comment]
Thank you so much! 👌👌👌👌
