### ISSUE TITLE
Integration tests in Gitlab CI pipeline (yes/no)

### ISSUE THREAD

**Issue by pertsevds** [jonnystorm/snmp-elixir#53]
It seems that "demo.snmplabs.com:1161" is in totaly down state, so i want to ask you, are you interested in integration tests in CI pipeline?
I now making snmpsim docker container that can be integrated into Gitlab CI pipeline, but i see that integration tests takes somewhat a longer time to execute and so i don't know if it's even reasonable to use them in CI.

**Comment by jonnystorm** [comment]
Yes, those endpoints have proven to be very unreliable.

I think CI is great place for these tests. I can think of no better way to ensure real SNMP requests will succeed.
