### ISSUE TITLE
Possibility to send snmp traps

### ISSUE THREAD

**Issue by D4no0** [jonnystorm/snmp-elixir#55]
Is it possible to send currently snmp traps using this library?
I couldn't find much information in erlang documentation about this either.

**Comment by jonnystorm** [comment]
This library is only intended for use by SNMP clients. However, see [these Erlang agent examples](http://erlang.org/doc/apps/snmp/snmp_impl_example_agent.html), particularly the bottom section, "Trap Sending."

Note that, while the above example is instructive, `send_trap` has been replaced by `send_notification`, and only the latter should be used. The documentation may be found [here](http://erlang.org/doc/man/snmpa.html#send_notification-3).

By all means, take whatever you can from `snmp_ex` to fill in the gaps. I wish you luck!
